creation_rules:
  - path_regex: .*$
    azure_keyvault: https://sops-b5078e18c0c34221.vault.azure.net/keys/sops-key/6e538f7c6d714d138226082070d1fe99
    pgp: 'FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4'
    #gcp_kms: 'projects/root-unison-284512/locations/global/keyRings/sops-testring/cryptoKeys/sops-key'
    #kms: 'arn:aws:kms:us-east-1:270047076664:key/c7546efc-d1ce-48af-b301-07e98266bd84'